### PR TITLE
Jamiecook/contains test case

### PR DESCRIPTION
**Pull request by jamiecook**
This PR demonstrates the problem I have been experiencing when doing a large number of "contains" operations with ```Geometry a``` types. I believe it's to do with the large number of conversions happening between the pure and raw forms, but can't be certain

On my macbook this test fails consistently within 20-40 polygons

```stack build --test```

image

### CODE REVIEW

**Comment by jamiecook** [comment]
It's now even worse than I thought... simply loading a lot of points and parsing them will randomly produce memory corruption. 

I thought that maybe it was to do with multiple geos contexts... so i wrote a version of readHex that does a bunch of bytestrings at once within the same context and with the same reader... but that seems to crash even harder than the other way. 

tbh I'm a bit out of my depth now.

**Comment by ewestern** [comment]
Hmmm,
This is a tough one. I'll do some profiling today and try to figure out where the segfault is happening. It's almost certainly *some* finalizer that's being called unexpectedly, but really not sure where that could be from looking at the code. Profile will be revealing, hopefully.

**Comment by ewestern** [comment]
So, the segfault seems to be consistently happening when accessing a coordinate sequence in getPosition. It seems likely that the memory for that coordinate sequence has been freed already by the time the c function "GEOSCoordSeq_getDimensions_r" is called. This happens even when ensuring that there is no finalizer attached to that coordinate sequence, suggesting that the finalizer for its parent geometry has already been called.
Not sure why this is only happening on the 8000th point in a sequence. Will have to dig in more later.

**Comment by ewestern** [comment]
Good news!
I think I've fixed this, or at least one manifestation of the problem. It's here in this PR, based off this branch. https://github.com/ewestern/geos/pull/13

Basically, I was using withForeignPtr improperly -- it only has guarantees for the finalizer running at the correct time for references to pointers used within it's block. I was returning a pointer to a coordinate sequence from this function. Even though that coordinate sequence didn't have a finalizer associated with it, once the function supplied to withForeignPtr completed, the RTS saw the parent geometry as safe to GC, and the finalizer was activated before subsequent functions had a chance to use the results.

I only tested this fix on profile/Profile.hs, which was based on one of your tests (and haven't tested on any of the others). I suspect there are other places where I used this anti-pattern, so I'll have to track those down. But now that I know the issue, it shouldn't be too hard to fix.

**Comment by jamiecook** [comment]
I think this one might be closed now... I believe all the fixes are in master

**Pull request closed without merging**
